/**
 * MBTI Atlas — Complete 16-type relationship & personality dataset
 */
const TEMPERAMENTS = {
  NT: { id: 'NT', name: '分析师', nameEn: 'Analysts', color: '#7c6cf0', glow: 'rgba(124,108,240,0.45)', icon: '🔬' },
  NF: { id: 'NF', name: '外交官', nameEn: 'Diplomats', color: '#4ecdc4', glow: 'rgba(78,205,196,0.45)', icon: '🕊️' },
  SJ: { id: 'SJ', name: '守护者', nameEn: 'Sentinels', color: '#5b9bd5', glow: 'rgba(91,155,213,0.45)', icon: '🛡️' },
  SP: { id: 'SP', name: '探险家', nameEn: 'Explorers', color: '#ff8c69', glow: 'rgba(255,140,105,0.45)', icon: '🌍' },
};

const MBTI_TYPES = {
  INTJ: {
    code: 'INTJ',
    name: '建筑师',
    nameEn: 'Architect',
    temperament: 'NT',
    dimensions: ['I', 'N', 'T', 'J'],
    tagline: '以远见筑造未来，以理性守护内心',
    animeArchetype: '冷静策士 · 黑长直智囊',
    animeRefs: ['牧濑红莉栖《命运石之门》', '利威尔《进击的巨人》', '夜神月《死亡笔记》'],
    avatarHue: 260,
    cognitive: 'Ni-Te-Fi-Se',
    description: 'INTJ 是罕见的战略思想家，善于看见系统全貌并制定长远计划。他们独立、果断，对无能与低效缺乏耐心，却在信任的人面前展现深沉忠诚。',
    strengths: ['战略眼光与系统思维', '高度自律与执行力', '诚实直接，重视真相', '在压力下保持冷静', '对承诺极其认真'],
    weaknesses: ['情感表达含蓄，易被误解冷漠', '过度自信或显得傲慢', '对细节琐事不耐烦', '社交能量有限', '难以接受非理性决策'],
    loveStyle: '恋爱前会做「可行性评估」，认定后极度专一。表达爱意偏实际行动：规划共同未来、解决问题，而非甜言蜜语。',
    loveNeeds: ['智力上的尊重与深度对话', '个人空间与独立', '真诚而非讨好', '目标一致的成长型关系'],
    bestPartner: ['ENFP', 'ENTP'],
    goodMatch: ['INFJ', 'ENTJ', 'INFP'],
    challenging: ['ESFJ', 'ISFP', 'ESFP'],
    friendship: '欣赏能挑战自己观点的智者；需要少数深度挚友而非泛泛之交。',
    career: ['科学家', '工程师', '战略顾问', '建筑师', '程序员', '投资分析'],
    stress: '被迫处理琐碎人情、计划被打乱、与情绪化却拒绝沟通的人相处。',
    growth: '练习表达感受；接受「足够好」；倾听他人情绪背后的需求。',
    famous: ['埃隆·马斯克', '尼采', '马克·扎克伯格'],
  },
  INTP: {
    code: 'INTP',
    name: '逻辑学家',
    nameEn: 'Logician',
    temperament: 'NT',
    dimensions: ['I', 'N', 'T', 'P'],
    tagline: '在思想的宇宙里，永远追问下一个为什么',
    animeArchetype: '慵懒天才 · 反差萌学者',
    animeRefs: ['L《死亡笔记》', '鹿目圆香《某科学的超电磁炮》式分析型', '奈良鹿丸《火影忍者》'],
    avatarHue: 245,
    cognitive: 'Ti-Ne-Si-Fe',
    description: 'INTP 热爱理论与抽象概念，是永不满足的好奇者。他们随和、低调，却在感兴趣的领域展现出惊人深度与创造力。',
    strengths: ['分析能力与逻辑严密', '创新思维与跨界联想', '客观公正', '适应变化', '对知识真诚的热爱'],
    weaknesses: ['拖延与执行力不足', '忽视现实细节与截止日期', '社交技巧生疏', '情绪难以捉摸', '容易过度怀疑'],
    loveStyle: '需要精神共鸣；可能用「辩论」表达亲密。害羞但深情，一旦打开心扉会非常忠诚。',
    loveNeeds: ['智力刺激', '不强迫社交', '接纳其古怪兴趣', '低压力的真诚沟通'],
    bestPartner: ['ENTJ', 'ENFJ'],
    goodMatch: ['ENTP', 'INTJ', 'INFJ'],
    challenging: ['ESFJ', 'ENFJ'],
    friendship: '与能一起探讨奇思妙想的人最合拍；讨厌肤浅的寒暄。',
    career: ['研究员', '程序员', '哲学家', '数据科学', '作家', '游戏设计'],
    stress: '重复性事务、情感绑架、被催促做决定。',
    growth: '设定小步deadline；主动表达关心；把想法落地为行动。',
    famous: ['爱因斯坦', '比尔·盖茨', '艾伦·图灵'],
  },
  ENTJ: {
    code: 'ENTJ',
    name: '指挥官',
    nameEn: 'Commander',
    temperament: 'NT',
    dimensions: ['E', 'N', 'T', 'J'],
    tagline: '领袖不是天生的，是被目标锻造的',
    animeArchetype: '王者气场 · 霸道总裁型',
    animeRefs: ['阿尔敏后期战略型', '鬼舞辻无惨式掌控（反面）', '利姆鲁决策面《关于我转生变成史莱姆这档事》'],
    avatarHue: 275,
    cognitive: 'Te-Ni-Se-Fi',
    description: 'ENTJ 是天生的组织者与推动者，善于动员资源、制定目标并带领团队前进。他们自信、果断，对低效零容忍。',
    strengths: ['领导力与决策力', '长远规划', '高效执行', '直言不讳推动进步', '在危机中挺身而出'],
    weaknesses: ['显得专横或缺乏耐心', '忽视他人感受', '工作狂倾向', '对失败容忍度低', '可能过于控制'],
    loveStyle: '主动追求、目标明确。希望伴侣是「人生战友」，一起征服世界。需要学会软化语气。',
    loveNeeds: ['独立且有能力的伴侣', '诚实反馈', '共同愿景', '尊重其雄心'],
    bestPartner: ['INTP', 'INFP'],
    goodMatch: ['ENTP', 'INTJ', 'ENFP'],
    challenging: ['ISFP', 'ISFJ'],
    friendship: '欣赏有才华、敢挑战自己的人；圈子常围绕事业与目标。',
    career: ['CEO', '律师', '管理咨询', '企业家', '政治家', '项目经理'],
    stress: '失去控制感、团队低效、感情用事却无逻辑。',
    growth: '倾听再决策；庆祝小胜利；练习共情式沟通。',
    famous: ['史蒂夫·乔布斯', '玛格丽特·撒切尔', '拿破仑'],
  },
  ENTP: {
    code: 'ENTP',
    name: '辩论家',
    nameEn: 'Debater',
    temperament: 'NT',
    dimensions: ['E', 'N', 'T', 'P'],
    tagline: '规则是用来打破的，想法是用来碰撞的',
    animeArchetype: '混沌好人 · 话痨发明家',
    animeRefs: ['五条悟《咒术回战》', '太宰治机智面', '坂田银时《银魂》'],
    avatarHue: 290,
    cognitive: 'Ne-Ti-Fe-Si',
    description: 'ENTP 机智、敏捷，热爱智力博弈与新点子。他们魅力十足、适应力强，是点子工厂，却可能对落地感到厌倦。',
    strengths: ['快速思维与即兴发挥', '创新与挑战现状', '说服力与幽默感', '广泛兴趣', '危机中的应变'],
    weaknesses: ['三分钟热度', '好辩伤感情', '忽视细节与承诺', '容易分心', '对例行公事厌烦'],
    loveStyle: '用玩笑与深度对话建立亲密；需要新鲜感。害怕无聊的关系，但认真时很浪漫。',
    loveNeeds: ['智力交锋', '自由与变化', '能接住梗的伴侣', '非控制型关系'],
    bestPartner: ['INFJ', 'INTJ'],
    goodMatch: ['INTP', 'ENTJ', 'ENFP'],
    challenging: ['ISFJ', 'ESFJ'],
    friendship: '朋友遍天下但知己少；最爱能一起「搞事」的伙伴。',
    career: ['创业者', '律师', '咨询', '营销', '发明家', '脱口秀/内容创作'],
    stress: '微观管理、无意义的规则、情感冷战却不说明原因。',
    growth: '完成比完美重要；辩论前问「对方需要赢吗」；培养耐心倾听。',
    famous: ['托马斯·爱迪生', '马克·吐温', '理查德·费曼'],
  },
  INFJ: {
    code: 'INFJ',
    name: '提倡者',
    nameEn: 'Advocate',
    temperament: 'NF',
    dimensions: ['I', 'N', 'F', 'J'],
    tagline: '看透人心的理想主义者，为信念默默燃烧',
    animeArchetype: '神秘治愈系 · 预言者',
    animeRefs: ['宇智波鼬', '绫波丽', '灶门炭治郎的深层共情面'],
    avatarHue: 165,
    cognitive: 'Ni-Fe-Ti-Se',
    description: 'INFJ 是稀少的洞察者与理想主义者，能感知他人未说出口的情绪，并致力于让世界变得更好。他们温柔却坚定。',
    strengths: ['深刻洞察与同理心', '坚定价值观', '创造性解决问题', '一对一深度连接', '长远愿景'],
    weaknesses: ['易情绪耗竭', '完美主义', '回避冲突后爆发', '过度吸收他人情绪', '难以被真正了解'],
    loveStyle: '追求灵魂伴侣式连接；浪漫且专一。需要安全感与深度理解，厌恶肤浅暧昧。',
    loveNeeds: ['情感真诚', '精神深度', '尊重其独处', '价值观一致'],
    bestPartner: ['ENTP', 'ENFP'],
    goodMatch: ['INTJ', 'INFP', 'ENFJ'],
    challenging: ['ESTP', 'ESFP'],
    friendship: '朋友不多但极深；是天然的倾听者与人生顾问。',
    career: ['心理咨询', '作家', '教师', '非营利', 'UX研究', '艺术治疗'],
    stress: '价值观被践踏、虚伪社交、长期情感忽视。',
    growth: '设定边界；接受不完美关系；直接表达需求而非期待对方猜到。',
    famous: ['马丁·路德·金', '特蕾莎修女', '甘地'],
  },
  INFP: {
    code: 'INFP',
    name: '调停者',
    nameEn: 'Mediator',
    temperament: 'NF',
    dimensions: ['I', 'N', 'F', 'P'],
    tagline: '内心住着整个宇宙，用温柔对抗世界',
    animeArchetype: '治愈天使 · 泪点担当',
    animeRefs: ['薇尔莉特《紫罗兰永恒花园》', '夏目贵志', '宫园薰《四月是你的谎言》'],
    avatarHue: 150,
    cognitive: 'Fi-Ne-Si-Te',
    description: 'INFP 是理想主义的治愈者，以内在价值观导航人生。他们富有想象力、同理心强，追求真实与意义胜过世俗成功。',
    strengths: ['真诚与共情', '创造力与写作天赋', '开放包容', '忠于信念', '看见他人独特光芒'],
    weaknesses: ['过度敏感', '逃避现实冲突', '拖延与优柔寡断', '自我批评严重', '难拒绝他人'],
    loveStyle: '恋爱像写一首诗——慢热、深情、浪漫到极致。需要被看见灵魂，而非只被欣赏外表。',
    loveNeeds: ['情感安全', '被理解而非被改造', '浪漫与仪式感', '尊重其价值观'],
    bestPartner: ['ENFJ', 'ENTJ'],
    goodMatch: ['INFJ', 'ENFP', 'INTJ'],
    challenging: ['ESTJ', 'ISTJ'],
    friendship: '三两知己胜过百个熟人；对虚伪零容忍。',
    career: ['作家', '心理咨询', '艺术', '社工', '翻译', '独立创作'],
    stress: '被批评人格、功利环境、强迫违背价值观。',
    growth: '把理想拆成可执行步骤；练习建设性冲突；自我关怀非自私。',
    famous: ['威廉·莎士比亚', 'J·K·罗琳', '梵高'],
  },
  ENFJ: {
    code: 'ENFJ',
    name: '主人公',
    nameEn: 'Protagonist',
    temperament: 'NF',
    dimensions: ['E', 'N', 'F', 'J'],
    tagline: '点燃他人潜能的太阳，温暖整个舞台',
    animeArchetype: '热血导师 · 团队之魂',
    animeRefs: ['炼狱杏寿郎', '艾伦·耶格尔早期', '御坂美琴的领袖面'],
    avatarHue: 175,
    cognitive: 'Fe-Ni-Se-Ti',
    description: 'ENFJ 是天生的激励者与组织者，善于看见他人潜力并凝聚人心。他们热情、负责，有时过度承担他人情绪。',
    strengths: ['领导力与感染力', '洞察他人需求', '沟通协调能力', '利他主义', '愿景驱动'],
    weaknesses: ['过度取悦他人', '忽视自我需求', '对批评敏感', '控制欲 disguised as help', '情绪化决策'],
    loveStyle: '全心投入、计划共同未来。表达爱意周到热烈，但需警惕「为你好」的过度干预。',
    loveNeeds: ['情感回应', '共同成长', '欣赏其付出', '稳定承诺'],
    bestPartner: ['INFP', 'ISFP'],
    goodMatch: ['ENFP', 'INFJ', 'INTP'],
    challenging: ['ISTP', 'ESTP'],
    friendship: '是朋友圈的粘合剂；乐于牵线搭桥、组织聚会。',
    career: ['教师', 'HR', '公关', '教练', '非营利领袖', '演员'],
    stress: '被冷漠对待、团队分裂、无法帮助他人时。',
    growth: '说「不」不是失败；区分「帮助」与「拯救」；独处充电。',
    famous: ['奥巴马', '奥普拉', '马丁·路德·金（双面）'],
  },
  ENFP: {
    code: 'ENFP',
    name: '竞选者',
    nameEn: 'Campaigner',
    temperament: 'NF',
    dimensions: ['E', 'N', 'F', 'P'],
    tagline: '用热情点亮世界，每一个灵魂都值得被看见',
    animeArchetype: '小太阳 · 元气冒险王',
    animeRefs: ['鸣人', '炭治郎', '工藤新一的热情面', '海绵宝宝式乐观'],
    avatarHue: 185,
    cognitive: 'Ne-Fi-Te-Si',
    description: 'ENFP 是自由的灵魂与创意源泉，充满热情、想象力与对人性的信念。他们连接力强，却可能难以专注一事。',
    strengths: ['热情与感染力', '创造力', '洞察人心', '适应力', '乐观精神'],
    weaknesses: ['注意力分散', '过度承诺', '逃避枯燥细节', '情绪起伏', '害怕被束缚'],
    loveStyle: '恋爱像冒险电影——浪漫、惊喜、深情。需要精神连接与自由空间的平衡。',
    loveNeeds: ['被认真对待', '探索式关系', '真诚与玩心并存', '不要窒息式控制'],
    bestPartner: ['INTJ', 'INFJ'],
    goodMatch: ['INFP', 'ENFJ', 'ENTJ'],
    challenging: ['ISTJ', 'ESTJ'],
    friendship: '朋友众多、圈子活跃；是派对灵魂与创意搭档。',
    career: ['记者', '演员', '创业', '咨询', '营销', '心理相关'],
    stress: '例行公事、冷漠环境、创意被否定。',
    growth: '培养专注力；跟进承诺；接受安静的日常也有美。',
    famous: ['罗宾·威廉姆斯', '威尔·史密斯', '昆汀·塔伦蒂诺'],
  },
  ISTJ: {
    code: 'ISTJ',
    name: '物流师',
    nameEn: 'Logistician',
    temperament: 'SJ',
    dimensions: ['I', 'S', 'T', 'J'],
    tagline: '沉默的脊梁，用责任撑起秩序',
    animeArchetype: '靠谱前辈 · 纪律委员',
    animeRefs: ['利威尔兵长面', '伏黑惠', '雪之下雪乃的严谨面'],
    avatarHue: 210,
    cognitive: 'Si-Te-Fi-Ne',
    description: 'ISTJ 是可靠的事实与规则守护者，重视传统、责任与承诺。他们务实、细致，是组织中坚，却可能抗拒突变。',
    strengths: ['可靠与尽责', '注重细节与流程', '诚实正直', '冷静务实', '长期稳定'],
    weaknesses: ['固执保守', '情感表达生硬', '抗拒变化', '显得冷漠', '难以放松'],
    loveStyle: '用行动证明爱：记得承诺、照顾生活细节。慢热但极忠诚，需要耐心融化冰山。',
    loveNeeds: ['忠诚与可预测', '尊重其规则', '务实而非空谈', '稳定家庭感'],
    bestPartner: ['ESFP', 'ESTP'],
    goodMatch: ['ISFJ', 'ESTJ', 'ENFP'],
    challenging: ['ENFP', 'INFP'],
    friendship: '朋友少而久；重视信义与共同经历。',
    career: ['会计', '审计', '军事', '法律执行', '工程管理', '银行'],
    stress: '混乱无序、言而无信、被迫即兴。',
    growth: '尝试小步改变；表达欣赏；理解「不同」不等于「错误」。',
    famous: ['乔治·华盛顿', '沃伦·巴菲特', '安吉拉·默克尔'],
  },
  ISFJ: {
    code: 'ISFJ',
    name: '守卫者',
    nameEn: 'Defender',
    temperament: 'SJ',
    dimensions: ['I', 'S', 'F', 'J'],
    tagline: '温柔的力量，默默守护每一个在乎的人',
    animeArchetype: '治愈系妈妈/爸爸 · 守护天使',
    animeRefs: ['日向雏田', '祢豆子式守护', '间桐樱的温柔面（正面）'],
    avatarHue: 200,
    cognitive: 'Si-Fe-Ti-Ne',
    description: 'ISFJ 温暖、体贴，以具体行动照顾身边人。他们谦虚、勤勉，记住细节与喜好，是社会的默默守护者。',
    strengths: ['体贴周到', '可靠耐心', '观察力敏锐', '忠诚', '务实关怀'],
    weaknesses: ['过度牺牲自我', '回避冲突', '抗拒改变', '难说不', '积累怨气后爆发'],
    loveStyle: '通过照顾日常表达爱；需要安全感与感激。害怕被抛弃，需要明确承诺。',
    loveNeeds: ['稳定与忠诚', '被感谢', '温和沟通', '家庭温馨'],
    bestPartner: ['ESFP', 'ESTP'],
    goodMatch: ['ISTJ', 'ESFJ', 'ISFP'],
    challenging: ['ENTP', 'INTP'],
    friendship: '长久贴心的闺蜜/兄弟型；记得每个朋友的生日。',
    career: ['护士', '教师', '行政', '图书馆', '室内设计', '客户服务'],
    stress: '被忽视付出、冲突激烈、环境剧变。',
    growth: '优先自我需求；直接表达不满；接受求助不是软弱。',
    famous: ['特蕾莎修女', '凯特王妃', '碧昂丝（舞台下）'],
  },
  ESTJ: {
    code: 'ESTJ',
    name: '总经理',
    nameEn: 'Executive',
    temperament: 'SJ',
    dimensions: ['E', 'S', 'T', 'J'],
    tagline: '秩序即正义，效率即美德',
    animeArchetype: '严师型长官 · 学生会主席',
    animeRefs: ['炼狱杏寿郎的纪律面', '阿尔冯斯·艾尔利克务实面', '真岛大佑式管理'],
    avatarHue: 220,
    cognitive: 'Te-Si-Ne-Fi',
    description: 'ESTJ 是社区与组织的管理者，重视规则、效率与传统。他们直言不讳、负责，善于建立可执行的系统。',
    strengths: ['组织与管理', '果断执行', '诚实直接', '责任感', '社区建设'],
    weaknesses: ['固执', '缺乏灵活性', '显得严厉', '忽视情感', '控制欲'],
    loveStyle: '传统、明确：追求稳定关系与家庭角色。需学习软化批评、倾听感受。',
    loveNeeds: ['尊重与忠诚', '共同目标', '井井有条的生活', '直言不讳的沟通'],
    bestPartner: ['ISFP', 'ISTP'],
    goodMatch: ['ISTJ', 'ENTJ', 'INTP'],
    challenging: ['INFP', 'ENFP'],
    friendship: '重视「有用」与靠谱的朋友；常是圈子组织者。',
    career: ['高管', '法官', '军官', '项目经理', '销售管理', '政治'],
    stress: '懒散无序、规则被蔑视、感情用事破坏计划。',
    growth: '问「感受如何」再建议；允许例外；庆祝非效率的瞬间。',
    famous: ['米歇尔·奥巴马', '约翰·洛克菲勒', '希拉里'],
  },
  ESFJ: {
    code: 'ESFJ',
    name: '执政官',
    nameEn: 'Consul',
    temperament: 'SJ',
    dimensions: ['E', 'S', 'F', 'J'],
    tagline: '聚光灯下的温暖，让每个人都感到被需要',
    animeArchetype: '人气王 · 妈妈式朋友',
    animeRefs: ['甘露寺蜜璃', '铃木园子', '樱兰高校 host 母性面'],
    avatarHue: 195,
    cognitive: 'Fe-Si-Ne-Ti',
    description: 'ESFJ 热心、合群，是社交场合的润滑剂。他们关注他人感受、维护和谐，有时过度在意他人评价。',
    strengths: ['温暖合群', ' practical 关怀', '组织活动', '忠诚', '观察社交细节'],
    weaknesses: ['过度在意评价', '难接受批评', '八卦倾向', '控制社交圈', '忽视深层问题'],
    loveStyle: '热烈、传统、乐于为伴侣付出。需要公开认可与仪式感，害怕冷战。',
    loveNeeds: ['情感表达', '社交认同', '稳定承诺', '被需要感'],
    bestPartner: ['ISFP', 'ISTP'],
    goodMatch: ['ISFJ', 'ENFJ', 'ESFP'],
    challenging: ['INTP', 'ENTP'],
    friendship: '朋友圈核心；记得所有人的梗与喜好。',
    career: ['护士', '教师', '活动统筹', '人力资源', '零售管理', '公关'],
    stress: '被排斥、关系破裂、冷漠伴侣。',
    growth: '独处反思；接受不是人人都会喜欢你；深入而非广度社交。',
    famous: ['泰勒·斯威夫特', '比尔·克林顿', '詹妮弗·洛佩兹'],
  },
  ISTP: {
    code: 'ISTP',
    name: '鉴赏家',
    nameEn: 'Virtuoso',
    temperament: 'SP',
    dimensions: ['I', 'S', 'T', 'P'],
    tagline: '冷静的观察者，用技艺征服世界',
    animeArchetype: '酷盖 · 技术宅刀客',
    animeRefs: ['索隆', '利威尔', '灰原哀冷静面', '宇智波佐助战斗面'],
    avatarHue: 25,
    cognitive: 'Ti-Se-Ni-Fe',
    description: 'ISTP 是冷静的工匠与问题解决者，擅长读懂机械与局势。他们低调、独立，用行动而非言语证明自己。',
    strengths: ['冷静应变', '动手能力', '逻辑分析', '独立自主', '危机处理'],
    weaknesses: ['情感疏离', '冒险冲动', '承诺恐惧', '容易无聊', '难表达内心'],
    loveStyle: '需要空间与尊重；爱通过共同冒险、帮忙修东西表达。讨厌粘腻与戏剧化。',
    loveNeeds: ['自由', '低 drama', '真诚直接', '共同兴趣'],
    bestPartner: ['ESFJ', 'ESTJ'],
    goodMatch: ['ESTP', 'ISTJ', 'ISFP'],
    challenging: ['ENFJ', 'INFJ'],
    friendship: '一起打游戏、运动、拆机的兄弟型；少言但靠谱。',
    career: ['工程师', '飞行员', '法医', '运动员', '特警', '程序员'],
    stress: '被情绪绑架、长期规划束缚、虚伪社交。',
    growth: '用语言确认在乎；规划长期目标；倾听他人感受非软弱。',
    famous: ['克林特·伊斯特伍德', '迈克尔·乔丹', '汤姆·克鲁斯'],
  },
  ISFP: {
    code: 'ISFP',
    name: '探险家',
    nameEn: 'Adventurer',
    temperament: 'SP',
    dimensions: ['I', 'S', 'F', 'P'],
    tagline: '活在当下的艺术家，美是唯一的语言',
    animeArchetype: '文艺少年 · 天然系',
    animeRefs: ['艾伦·耶格尔自由面', '桐谷和人温柔面', '风太郎早期的艺术感'],
    avatarHue: 35,
    cognitive: 'Fi-Se-Ni-Te',
    description: 'ISFP 温和、敏感，用审美与行动表达自我。他们活在当下，厌恶冲突与束缚，拥有安静而强烈的内心世界。',
    strengths: ['审美与创造力', '温柔包容', '灵活适应', '真诚', '危机中的冷静'],
    weaknesses: ['过度敏感', '回避规划', '难说不', '容易退缩', '自我批评'],
    loveStyle: '浪漫而含蓄；需要温柔与耐心。用行动与礼物表达爱，害怕被批评或控制。',
    loveNeeds: ['尊重个性', '温柔沟通', '共同体验美', '非评判空间'],
    bestPartner: ['ENFJ', 'ESFJ'],
    goodMatch: ['ESTP', 'ESFP', 'ISFJ'],
    challenging: ['ENTJ', 'INTJ'],
    friendship: '少数知心；一起听音乐、旅行、创作的伙伴。',
    career: ['设计师', '摄影师', '厨师', '兽医', '护士', '艺术家'],
    stress: '被批评作品/人格、长期冲突、功利环境。',
    growth: '表达需求；做长期财务/职业规划；建设性面对批评。',
    famous: ['迈克尔·杰克逊', '碧昂丝', '莫扎特'],
  },
  ESTP: {
    code: 'ESTP',
    name: '企业家',
    nameEn: 'Entrepreneur',
    temperament: 'SP',
    dimensions: ['E', 'S', 'T', 'P'],
    tagline: '人生是竞技场，赢家享受当下',
    animeArchetype: '行动派帅哥 · 运动番王牌',
    animeRefs: ['坂田银时战斗面', '流川枫', '承太郎'],
    avatarHue: 15,
    cognitive: 'Se-Ti-Fe-Ni',
    description: 'ESTP 大胆、务实，是现场的反应大师。他们享受刺激、社交与竞争，善于说服与即兴发挥。',
    strengths: ['行动力', '社交魅力', '应变力', '现实主义', '说服力强'],
    weaknesses: ['冲动冒险', '耐心不足', '忽视长远', '可能伤人不顾感受', '厌倦承诺'],
    loveStyle: '热烈、直接、爱带伴侣体验刺激。需学习深度倾听与长期承诺。',
    loveNeeds: ['新鲜感', '独立空间', '诚实', '一起玩的伙伴感'],
    bestPartner: ['ISFJ', 'ISTJ'],
    goodMatch: ['ISTP', 'ESFP', 'ENTJ'],
    challenging: ['INFJ', 'INTJ'],
    friendship: '派对中心、运动队友；讨厌矫情与长篇大论。',
    career: ['销售', '创业', '急救', '运动员', '警察', '谈判'],
    stress: '长期独处、抽象理论、被限制自由。',
    growth: '思考后果；培养耐心；认真面对他人情绪。',
    famous: ['唐纳德·特朗普', '麦当娜', '杰克·尼科尔森'],
  },
  ESFP: {
    code: 'ESFP',
    name: '表演者',
    nameEn: 'Entertainer',
    temperament: 'SP',
    dimensions: ['E', 'S', 'F', 'P'],
    tagline: '世界是我的舞台，快乐是最好的礼物',
    animeArchetype: '派对之星 · 搞笑担当',
    animeRefs: ['善逸', '张楚岚', '甘露寺蜜璃活力面', '星野爱'],
    avatarHue: 45,
    cognitive: 'Se-Fi-Te-Ni',
    description: 'ESFP 活力四射、热爱当下，是天然的表演者与气氛制造者。他们慷慨、友善，用感官体验拥抱生活。',
    strengths: ['乐观热情', '审美与表演', '人际连接', '灵活', '慷慨'],
    weaknesses: ['回避严肃话题', '冲动消费', '难做长期规划', '害怕孤独', '敏感于批评'],
    loveStyle: '浪漫、惊喜、身体语言丰富。需要欣赏与陪伴，厌恶冷漠与批评式沟通。',
    loveNeeds: ['关注与赞美', '共同玩乐', '情感表达', '包容其起伏'],
    bestPartner: ['ISTJ', 'ISFJ'],
    goodMatch: ['ISTP', 'ESTP', 'ESFJ'],
    challenging: ['INTJ', 'INFJ'],
    friendship: '人人爱的开心果；组织聚会、带动气氛。',
    career: ['演员', '主持', '时尚', '旅游', '活动策划', '幼教'],
    stress: '被忽视、长期严肃环境、财务压力无出口。',
    growth: '面对困难对话；储蓄与规划；独处也能自洽。',
    famous: ['玛丽莲·梦露', '埃尔顿·约翰', '杰米·福克斯'],
  },
};

/** Build compatibility edges for graph */
function buildEdges() {
  const edges = [];
  const seen = new Set();

  Object.values(MBTI_TYPES).forEach((type) => {
    type.bestPartner.forEach((target) => {
      const key = [type.code, target].sort().join('-');
      if (!seen.has(key)) {
        seen.add(key);
        edges.push({ source: type.code, target, tier: 'best', weight: 3 });
      }
    });
    type.goodMatch.forEach((target) => {
      const key = [type.code, target].sort().join('-');
      if (!seen.has(key)) {
        seen.add(key);
        edges.push({ source: type.code, target, tier: 'good', weight: 2 });
      }
    });
    type.challenging.forEach((target) => {
      const key = [type.code, target].sort().join('-');
      if (!seen.has(key)) {
        seen.add(key);
        edges.push({ source: type.code, target, tier: 'challenge', weight: 1 });
      }
    });
  });
  return edges;
}

const COMPATIBILITY_EDGES = buildEdges();

const DIMENSION_LABELS = {
  E: '外向 Extraversion',
  I: '内向 Introversion',
  S: '实感 Sensing',
  N: '直觉 Intuition',
  T: '思考 Thinking',
  F: '情感 Feeling',
  J: '判断 Judging',
  P: '感知 Perceiving',
};

/** Legendary pairs for spotlight */
const LEGENDARY_PAIRS = [
  { a: 'INTJ', b: 'ENFP', title: '战略家 × 追梦人', desc: '互补的黄金组合：远见与热情、逻辑与情感完美平衡，被誉为最高兼容度之一。' },
  { a: 'INFJ', b: 'ENTP', title: '洞察者 × 辩论家', desc: '深度灵魂碰撞：一方读懂人心，一方点燃思维火花。' },
  { a: 'INFP', b: 'ENTJ', title: '诗人 × 指挥官', desc: '理想与执行的结合：价值观遇见行动力。' },
  { a: 'ISFJ', b: 'ESFP', title: '守护者 × 表演者', desc: '安稳遇见活力：体贴照顾与阳光陪伴的温馨组合。' },
];
